### ISSUE TITLE
@Asset freeze with @Journal

### ISSUE THREAD

**Issue by diablonhn** [baratine/baratine#3]
@Asset + @Journal           = freeze
@Asset + @Journal + @OnLoad = no freeze

See: QvaultJournalTest

Problem with vault+@Journal?  The @OnLoad bypasses the vault.

**Comment by diablonhn** [comment]
Maybe related?

[2016-09-12 06:19:48,531] {/BookStoreOnLoad@20} FINER DeliverInbox: com.caucho.v5.h3.io.H3ExceptionIn: Zero-arg constructor required for com.caucho.v5.web.webapp.RequestBaratineImpl
                          com.caucho.v5.h3.io.H3ExceptionIn: Zero-arg constructor required for com.caucho.v5.web.webapp.RequestBaratineImpl
                          	at com.caucho.v5.h3.ser.SerializerH3Java.introspectConstructor(SerializerH3Java.java:159)
                          	at com.caucho.v5.h3.ser.SerializerH3Java.introspect(SerializerH3Java.java:119)
                          	at com.caucho.v5.h3.context.ContextH3Impl.serializer(ContextH3Impl.java:108)
                          	at com.caucho.v5.h3.context.ContextH3Impl.serializer(ContextH3Impl.java:37)
                          	at com.caucho.v5.h3.io.OutH3Impl.serializer(OutH3Impl.java:147)
                          	at com.caucho.v5.h3.io.OutH3Impl.writeObject(OutH3Impl.java:163)
                          	at com.caucho.v5.amp.journal.JournalImpl.writeSend(JournalImpl.java:230)
                          	at com.caucho.v5.amp.journal.StubStateJournal.send(StubStateJournal.java:135)
                          	at com.caucho.v5.amp.message.SendMessage_N.invoke(SendMessage_N.java:105)
                          	at com.caucho.v5.amp.inbox.DeliverInbox.deliver(DeliverInbox.java:104)
                          	at com.caucho.v5.amp.inbox.DeliverInboxDebug.deliver(DeliverInboxDebug.java:63)
                          	at com.caucho.v5.amp.inbox.DeliverInboxDebug.deliver(DeliverInboxDebug.java:40)
                          	at com.caucho.v5.amp.queue.QueueRingFixed.deliver(QueueRingFixed.java:360)
                          	at com.caucho.v5.amp.queue.QueueRingResizing.deliver(QueueRingResizing.java:274)
                          	at com.caucho.v5.amp.deliver.WorkerDeliverDisruptor.runImpl(WorkerDeliverDisruptor.java:110)
                          	at com.caucho.v5.amp.deliver.WorkerDeliverBase.runStarted(WorkerDeliverBase.java:257)
                          	at com.caucho.v5.amp.deliver.WorkerDeliverBase.runAs(WorkerDeliverBase.java:193)
                          	at com.caucho.v5.amp.deliver.OutboxImpl.flushAndExecuteAll(OutboxImpl.java:124)
                          	at com.caucho.v5.amp.thread.ThreadAmp.runTasks(ThreadAmp.java:194)
                          	at com.caucho.v5.amp.thread.ThreadAmp.run(ThreadAmp.java:154)

**Comment by carojkov** [comment]
I think @Journal shouldn't be used on @Get/@Post and other HTTP methods,
because the client connection will have been gone when journal replays.
